name: lore
version: 0.0.0.0
license: MIT
github: adelon/naproche-cic

extra-source-files:
  - readme.md
  - license.md

dependencies:
  - base-noprelude
  - base-prelude
  - containers
  - directory
  - megaparsec
  - mtl
  - parser-combinators
  - prettyprinter
  - text
  - transformers
  - unordered-containers

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

ghc-options:
  - -Wall
  - -fno-warn-unused-do-bind

library:
  source-dirs: source/

executables:
  lore:
    main: Main.hs
    source-dirs: app/
    dependencies:
      - lore

tests:
  lore-test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
      - lore
      - hspec
      - hspec-megaparsec
