resolver: lts-15.0

# Stackage currently only has the 7.x series of megaparsec.
# We have a custom token stream, where the implementation would
# differ between 7.x/8.x, so we chose the more recent version.
extra-deps:
  - trie-simple-0.4.1.1
